config/routes.rb
Rails.application.routes.draw do
  get 'dogs/new'
  get 'posts/index'
  devise_for :users, controllers: {   registrations: 'users/registrations',
                                    sessions: 'users/sessions' }
  root "notes#index"
  resources :notes, only: [:index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :posts do
    resources :likes, :only => [:create, :destroy]
  end
  resources :users, :only => [:show,:index]
  resources :dogs, :only => [:create, :destroy, :update]
  resources :comments, :only => [:create, :destroy]
end

app/models/note.rb
class Note < ApplicationRecord
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]

  # GET /notes
  # GET /notes.json
  def index
    @users = User.with_attached_avatar
    @dogs = Dog.eager_load(:user).all.with_attached_avatar
    @posts = Post.all.with_attached_images
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
  end

  def signin
  end

  def login
  end

  def post
  end

  def user_index
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = Note.new(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to @note, notice: 'Note was successfully created.' }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url, notice: 'Note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:text)
    end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_header.html.erb
    <nav class="navbar navbar-expand-lg navbar-dark " style="background-color: #0b2345">
      <a class="navbar-brand mb-0 h1" href="/"><i class="fas fa-paw"></i>DOGGY.<span>com<span></a>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
        <% if user_signed_in? %>
        <ul class="navbar-nav ">
          <li class="nav-item">
            <a class="nav-link" href="/signin">User_name <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <%= link_to "ログアウト", destroy_user_session_path, class: "nav-link", method: :delete%>
          </li>

          <li class="nav-item">
            <a class="nav-link " href="#">ガイド</a>
          </li>
        </ul>
        <% else %>
        <ul class="navbar-nav ">
          <li class="nav-item">
            <a class="nav-link" href="/signin">新規会員登録 <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/login">ログイン</a>
          </li>

          <li class="nav-item">
            <a class="nav-link " href="#">ガイド</a>
          </li>
        </ul>
        <%end%>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        </form>
        <a class="nav-link logs" href="#"><img class="log" src="assets/f_log.png"></a>
        <a class="nav-link logs" href="#"><img class="log" src="assets/inst_log2.png"></a>
      </div>
    </nav>

    <div class="header_second" style="background-color: #0b2345">
      <ul class="nav list_nav">
        <li class="nav-item">
          <a class="nav-link newdogg" data-toggle="modal" data-target="#myModal">投稿する</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/post" id="dog_list" data-fader="0">みんなの投稿</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#" id="pick_up" data-fader="1">pick up</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#" id="shop" data-fader="2">shop</a>
        </li>
      </ul>

      <div class="modal fade" id="myModal2" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">ユーザー登録でDoggy.comをもっと便利に</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="閉じる">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <p>新規投稿にはログインが必要です</p>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" onclick="location.href='/login'">ログイン</button>
              <button type="button" class="btn btn-primary" onclick="location.href='/signin'">新規登録</button>
            </div>
          </div>
        </div>
      </div>

      <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">新規投稿する</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="閉じる">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <textarea rows="8" placeholder="テキスト"></textarea>
              <div>
                <input placeholder="#タグを追加"></input>
              </div>
              <div class="posted_images">
              </div>
              <div class="post__form-image">
                <button type="button" class="btn btn-light" id="image_post">画像を追加</button>
                <input type="file" name="image_file[]" multiple="multiple" id="image_post_input" class="hide"></input>
                <button type="button" class="btn btn-light">MyDoggyを選択</button>
              </div>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-primary">投稿する</button>
            </div>
          </div>
        </div>
      </div>





      <div class="fader hide" id="pick_up_fader" data-fader="1">
        <div class="img_layer">
          <img class="min_image" src="assets/puppy_cut">
          <img class="min_image" src="assets/pag_cut">
          <img class="min_image" src="assets/puppy_cut">
          <img class="min_image" src="assets/pag_cut">
        </div>
        <div class="img_layer">
          <img class="min_image" src="assets/pag_cut">
          <img class="min_image" src="assets/puppy_cut">
          <img class="min_image" src="assets/pag_cut">
          <img class="min_image" src="assets/puppy_cut">
        </div>

      </div>

      <div class="fader hide" id="shop_fader" data-fader="2">
        <div class="icon_layer">
          <a href="#">
            <i class="fas fa-bone fa-5x"></i>
            Foods
          </a>
          <a href="#">
            <i class="fas fa-cut fa-5x"></i>
            Groomers
          </a>
          <a href="#">
            <i class="fas fa-tshirt fa-5x"></i>
            Clothes
          </a>
          <a href="#">
            <i class="fas fa-baseball-ball fa-5x"></i>
            Toys
          </a>
        </div>

      </div>

    </div>

app/views/notes/index.html.erb
<%= render partial: "/modules/header"%>


<div class="notes grandPart">
  <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">

    <div class="carousel-inner">
      <div class="carousel-item active">
        <img class="d-block w-100" src="/images/dogs.jpg" alt="第1スライド">
      </div><!-- /.carousel-item -->
      <div class="carousel-item">
        <img class="d-block w-100" src="/images/puppy2.jpg" alt="第2スライド">
      </div><!-- /.carousel-item -->
      <div class="carousel-item">
        <img class="d-block w-100" src="/images/pag.jpg" alt="第3スライド">
      </div>
      <!-- スライドコントロールの設定 -->
      <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">前へ</span>
      </a>
      <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">次へ</span>
      </a>
    </div>
  </div>


  <div class="main1 container-fluid">
    <div class="titles">
      <em class="h1">Pickup Dogs</em>
    </div>

    <div class="row ">
      <div class="col-xs-0 col-sm-2 col-md-2 cards">
      </div>

      <%@dogs.each_with_index do |dog,index|%>
      <div class="col-xs-2 col-sm-6 col-md-2 cards">
        <%=link_to user_path(dog.user.id),class: "card picked_dog" do%>
        <%= image_tag dog.avatar.variant(combine_options:{resize:"200x200^",crop:"200x200+0+0",gravity: :center}).processed%>
        <div class="card-img-overlay hide">
          <img class="arrow_icon" src="/images/arrow_icon.png">
          <h5 class="card-title">@<%=dog.user.name%></h5>
          <p class="card-text"><small><%=dog.name%></small></p>
        </div>
        <%end%>
      </div>
      <%if index == 3%>
      <%break%>
      <%end%>
      <%end%>

    </div>
    <div class="row row-underline" id="media_hide">
      <div class="col-xs-0 col-sm-2 col-md-2 cards">
      </div>

      <%@dogs[4..7].each_with_index do |dog,index|%>
      <div class="col-xs-2 col-sm-6 col-md-2 cards">
        <%=link_to user_path(dog.user.id),class: "card picked_dog" do%>
        <%= image_tag dog.avatar.variant(combine_options:{resize:"200x200^",crop:"200x200+0+0",gravity: :center}).processed%>
        <div class="card-img-overlay hide">
          <img class="arrow_icon" src="/images/arrow_icon.png">
          <h5 class="card-title">@<%=dog.user.name%></h5>
          <p class="card-text"><small><%=dog.name%></small></p>
        </div>
        <%end%>
      </div>
      <%if index == 3%>
      <%break%>
      <%end%>
      <%end%>


    </div>

  </div>

  <div class="main2 container">
    <div class="titles">
      <em class="h1">人気ユーザー</em>
    </div>
    <div class="row">

      <div class="col-xs-1 col-sm-6 col-md-3 user1 cards">
        <%= link_to(user_path(@users[0].id)) do%>
        <div class="card img-thumbnail">
          <%= image_tag @users[0].avatar.variant(combine_options:{resize:"260x260^",crop:"260x260+0+0",gravity: :center}).processed %>
          <div class="card-body px-2 py-3">
            <h5 class="card-title">@<%=@users[0].name%></h5>
            <p class="card-text"><%=simple_format(@users[0].introduction)%></p>
          </div>
        </div>
        <%end%>
      </div>
      <div class="col-xs-1 col-sm-6 col-md-3 user2 cards">
        <%= link_to(user_path(@users[1].id)) do%>
        <div class="card img-thumbnail">
          <%= image_tag @users[1].avatar.variant(combine_options:{resize:"260x260^",crop:"260x260+0+0",gravity: :center}).processed %>
          <div class="card-body px-2 py-3">
            <h5 class="card-title">@<%=@users[1].name%></h5>
            <p class="card-text"><%=simple_format(@users[1].introduction)%></p>
          </div>
        </div>
        <%end%>
      </div>
      <div class=" col-xs-1 col-sm-6 col-md-3 user3 cards">
        <%= link_to(user_path(@users[2].id)) do %>
        <div class="card img-thumbnail">
          <%= image_tag @users[2].avatar.variant(combine_options:{resize:"260x260^",crop:"260x260+0+0",gravity: :center}).processed %>
          <div class="card-body px-2 py-3">
            <h5 class="card-title">@<%=@users[2].name%></h5>
            <p class="card-text"><%=simple_format(@users[2].introduction)%></p>
          </div>
        </div>
        <%end%>

      </div>
      <div class=" col-xs-1 col-sm-6 col-md-3 user3 cards">
        <%= link_to(user_path(@users[3].id)) do %>
        <div class="card img-thumbnail">
          <%= image_tag @users[3].avatar.variant(combine_options:{resize:"260x260^",crop:"260x260+0+0",gravity: :center}).processed %>
          <div class="card-body px-2 py-3">
            <h5 class="card-title">@<%=@users[3].name%></h5>
            <p class="card-text"><%=simple_format(@users[3].introduction)%></p>
          </div>
        </div>
        <%end%>

      </div>

    </div>


    <%=link_to "View more",users_path, class: "btn btn-primary btn-block container", role: "button"%>
  </div>
  <div class="main3 container-fluid">
    <div class="titles">
      <em class="h1">人気の投稿</em>
    </div>

    <div class="row">
      <div class="col-xs-2 col-sm-0 col-md-2 cards">
      </div>
      <%@posts.each_with_index do |post,index|%>
      <div class="col-xs-2 col-sm-6 col-md-2 cards">
        <%=link_to post_path(post.id),class: "card" do%>
        <%= image_tag post.images[0].variant(combine_options:{resize:"200x200^",crop:"200x200+0+0",gravity: :center}).processed%>
        <%end%>
      </div>
      <%if index == 3%>
      <%break%>
      <%end%>
      <%end%>
    </div>
    <div class="row" id="media_hide">
      <div class="col-xs-2 col-sm-0 col-md-2 cards">
      </div>

      <%@posts[4..7].each_with_index do |post,index|%>
      <div class="col-xs-2 col-sm-6 col-md-2 cards">
        <%=link_to post_path(post.id),class: "card" do%>
        <%= image_tag post.images[0].variant(combine_options:{resize:"200x200^",crop:"200x200+0+0",gravity: :center}).processed%>
        <%end%>
      </div>
      <%if index == 3%>
      <%break%>
      <%end%>
      <%end%>


    </div>
    <%=link_to "View more",posts_path, class: "btn btn-primary btn-block container", role: "button"%>
  </div>








  <div class="main4 container-fluid hide">
    <div class="titles">
      <em class="h1">Instagrams</em>
    </div>

    <div class="row">
      <div class="col-xs-2 col-sm-0 col-md-2 cards">
      </div>

      <div class="col-xs-2 col-sm-6 col-md-2 cards">
        <a href="#" class="card">
          <img class="card-img" src="/images/love.png" alt="インスタ">
        </a>

      </div>
      <div class="col-xs-2 col-sm-6 col-md-2 cards">
        <a href="#" class="card">
          <img class="card-img" src="/images/love.png" alt="インスタ">
        </a>

      </div>
      <div class="col-xs-2 col-sm-6 col-md-2 cards">
        <a href="#" class="card">
          <img class="card-img" src="/images/love.png" alt="インスタ">
        </a>

      </div>
      <div class="col-xs-2 col-sm-6 col-md-2 cards">
        <a href="#" class="card">
          <img class="card-img" src="/images/love.png" alt="インスタ">
        </a>

      </div>

    </div>



  </div>
  <div class="dog-icon">
    <i class="fas fa-dog fa-3x "></i>
  </div>

</div>

<%= render partial: "/modules/footer"%>

app/views/notes/post.html.erb
<%= render partial: "/modules/header"%>
<div class="post grandPart">
  <div class="container-fluid post__mainContent">

    <div class="row post_row ">
      <div class="col-xs-0 col-sm-0 col-md-1 ">
      </div>

      <div class="post_row_left col-xs-12 col-sm-12 col-md-2 ">
        <div class="post__user">
          <i class="fas fa-user-circle fa-3x"></i>
          <div class="post__user-name">
            <p class="post__user-name_user">User_name</p>
            <p class="post__user-name_dog">Dog_name</p>
          </div>

        </div>
        <div class="post__pickedUser">
          <div class="post__pickedUser-title">
            <p class="osusume">おすすめ</p>
            <a href="/user_index" class="subete">すべて見る</a>
          </div>
          <div class="post__pickedUser-user">
            <i class="fas fa-user-circle fa-2x"></i>
            <a class="user_name" href="#">User_name</a>
          </div>
          <div class="post__pickedUser-user">
            <i class="fas fa-user-circle fa-2x"></i>
            <a class="user_name" href="#">User_name</a>
          </div>
          <div class="post__pickedUser-user">
            <i class="fas fa-user-circle fa-2x"></i>
            <a class="user_name" href="#">User_name</a>
          </div>

        </div>
      </div>
      <div class="post_row_right col-xs-12 col-sm-6 ">
        <%= render partial:"postContent", locals: {id: "1"}%>
        <%= render partial:"postContent", locals: {id: "2"}%>
        <%= render partial:"postContent", locals: {id: "3"}%>
        <%= render partial:"postContent", locals: {id: "4"}%>
      </div>

    </div>
  </div>
</div>

<%= render partial:"/modules/footer"%>

app/views/notes/tweet_show.html.erb
<%= render partial: "header"%>
<div class="post grandPart">
  <div class="container-fluid post__mainContent">
    <div class="row post_row ">

      <div class="post_row_left col-xs-12 col-sm-12 col-md-3 ">
      </div>

      <div class="post_row_right col-xs-12 col-sm-6 ">

        <div class="post__maincontent-posts">
          <div class="post__maincontent-posts-title">
            <i class="fas fa-user-circle fa-2x"></i>
            <a class="user_name" href="/user_show">User_name</a>
            <div class="fas-modifier">
              <a href="#" role="button" id="dropdownMenuLink1" data-toggle="dropdown" aria-haspopup="true"
                aria-expanded="false"><i class="fas fa-ellipsis-v"></i></a>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuLink1">
                <a class="dropdown-item" href="/tweet_show">詳細</a>
                <a class="dropdown-item" href="#">削除</a>
              </div>
            </div>
          </div>
          <div class="post__maincontent-posts-image">
            <div id="carouselExampleControls1h" class="carousel slide">

              <div class="carousel-inner">
                <div class="carousel-item active">
                  <img class="d-block w-100" src="/assets/pag.jpg" alt="第1スライド">
                </div>
                <div class="carousel-item">
                  <img class="d-block w-100" src="/assets/pag.jpg" alt="第2スライド">
                </div>
                <div class="carousel-item">
                  <img class="d-block w-100" src="/assets/pag.jpg" alt="第3スライド">
                </div>
              </div>

              <a class="carousel-control-prev" href="#carouselExampleControls1h" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">前へ</span>
              </a>
              <a class="carousel-control-next" href="#carouselExampleControls1h" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">次へ</span>
              </a>
            </div>
          </div>
          <div class="post__maincontent-posts-icons">
            <a href="#" class="post__maincontent-posts-icons-a"><i class="far fa-heart fa-2x"></i></a><span>12</span>
            <a href="#" class="post__maincontent-posts-icons-a"><i class="far fa-comment fa-2x"></i></a><span>12</span>
          </div>
          <div class="post__maincontent-posts-text">
            犬犬犬犬犬犬犬犬犬犬犬犬犬
            <br>犬犬犬犬犬犬犬犬犬犬犬犬犬犬犬犬犬犬犬犬犬犬犬犬犬犬
            <br>犬犬犬犬犬犬犬犬犬犬犬犬犬犬犬犬犬犬犬犬犬犬犬犬犬犬
            <div class="post__maincontent-posts-hash">
              <a href="#">#パグ </a><a href="#">#パグ</a> <a href="#">#パグ</a> <a href="#">#パグ</a>
            </div>
          </div>
          <div class="post__maincontent-posts-comments">
            <div class="post__maincontent-posts-comments-comment">
              <div class="post__maincontent-posts-comments-comment-user">
                <i class="fas fa-user-circle fa-2x"></i>
                <a class="user_name" href="#">User_name</a>
              </div>
              <div class="post__maincontent-posts-comments-comment-text">
                かわいい
              </div>
            </div>
            <div class="post__maincontent-posts-comments-comment">
              <div class="post__maincontent-posts-comments-comment-user">
                <i class="fas fa-user-circle fa-2x"></i>
                <a class="user_name" href="#">User_name</a>
              </div>
              <div class="post__maincontent-posts-comments-comment-text">
                かわいい
              </div>
            </div>
            <div class="post__maincontent-posts-comments-comment">
              <div class="post__maincontent-posts-comments-comment-user">
                <i class="fas fa-user-circle fa-2x"></i>
                <a class="user_name" href="#">User_name</a>
              </div>
              <div class="post__maincontent-posts-comments-comment-text">
                かわいい
              </div>
            </div>
            <div class="post__maincontent-posts-comments-comment">
              <div class="post__maincontent-posts-comments-comment-user">
                <i class="fas fa-user-circle fa-2x"></i>
                <a class="user_name" href="#">User_name</a>
              </div>
              <div class="post__maincontent-posts-comments-comment-text">
                かわいい
              </div>
            </div>
          </div>
          <div class="post__maincontent-posts-commentform">
            <input placeholder="コメントを入力...."></input>
          </div>

        </div>

      </div>
    </div>
  </div>
</div>



<%= render partial: "footer"%>

app/views/notes/user_index.html.erb
<%= render partial: "header"%>
<div class="user_index grandPart">
  <div class="container-fluid">
    <div class="row user_index__row">
      <div class="col-xs-12 col-sm-12 col-md-4">
      </div>
      <div class="col-xs-12 col-sm-12 col-md-4 main">
        <div class="main__title">
          ユーザー
        </div>
        <div class="main__serchbox">
          <input type="email" class="form-control" id="exampleInputEmail1" placeholder="検索">
        </div>
        <div class="main__users">
          <div class="main__users-user">
            <i class="fas fa-user-circle fa-2x"></i>
            <div class="main__users-user-name">
              <a class="user_name" href="#">User_name</a>
              <div class="dog_name" href="#">Dog_name</div>
            </div>
          </div>
          <div class="main__users-user">
            <i class="fas fa-user-circle fa-2x"></i>
            <div class="main__users-user-name">
              <a class="user_name" href="#">User_name</a>
              <div class="dog_name" href="#">Dog_name</div>
            </div>
          </div>
          <div class="main__users-user">
            <i class="fas fa-user-circle fa-2x"></i>
            <div class="main__users-user-name">
              <a class="user_name" href="#">User_name</a>
              <div class="dog_name" href="#">Dog_name</div>
            </div>
          </div>
          <div class="main__users-user">
            <i class="fas fa-user-circle fa-2x"></i>
            <div class="main__users-user-name">
              <a class="user_name" href="#">User_name</a>
              <div class="dog_name" href="#">Dog_name</div>
            </div>
          </div>
          <div class="main__users-user">
            <i class="fas fa-user-circle fa-2x"></i>
            <div class="main__users-user-name">
              <a class="user_name" href="#">User_name</a>
              <div class="dog_name" href="#">Dog_name</div>
            </div>
          </div>
          <div class="main__users-user">
            <i class="fas fa-user-circle fa-2x"></i>
            <div class="main__users-user-name">
              <a class="user_name" href="#">User_name</a>
              <div class="dog_name" href="#">Dog_name</div>
            </div>
          </div>
          <div class="main__users-user">
            <i class="fas fa-user-circle fa-2x"></i>
            <div class="main__users-user-name">
              <a class="user_name" href="#">User_name</a>
              <div class="dog_name" href="#">Dog_name</div>
            </div>
          </div>
          <div class="main__users-user">
            <i class="fas fa-user-circle fa-2x"></i>
            <div class="main__users-user-name">
              <a class="user_name" href="#">User_name</a>
              <div class="dog_name" href="#">Dog_name</div>
            </div>
          </div>
          <div class="main__users-user">
            <i class="fas fa-user-circle fa-2x"></i>
            <div class="main__users-user-name">
              <a class="user_name" href="#">User_name</a>
              <div class="dog_name" href="#">Dog_name</div>
            </div>
          </div>
          <div class="main__users-user">
            <i class="fas fa-user-circle fa-2x"></i>
            <div class="main__users-user-name">
              <a class="user_name" href="#">User_name</a>
              <div class="dog_name" href="#">Dog_name</div>
            </div>
          </div>
          <div class="main__users-user">
            <i class="fas fa-user-circle fa-2x"></i>
            <div class="main__users-user-name">
              <a class="user_name" href="#">User_name</a>
              <div class="dog_name" href="#">Dog_name</div>
            </div>
          </div>
          <div class="main__users-user">
            <i class="fas fa-user-circle fa-2x"></i>
            <div class="main__users-user-name">
              <a class="user_name" href="#">User_name</a>
              <div class="dog_name" href="#">Dog_name</div>
            </div>
          </div>


        </div>
      </div>
    </div>
  </div>
</div>
<%= render partial:"footer"%>