config/routes.rb
Rails.application.routes.draw do
  get 'dogs/new'
  get 'posts/index'
  devise_for :users, controllers: {   registrations: 'users/registrations',
                                    sessions: 'users/sessions' }
  root "notes#index"
  resources :notes, only: [:index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :posts do
    resources :likes, :only => [:create, :destroy]
  end
  resources :users, :only => [:show,:index]
  resources :dogs, :only => [:create, :destroy, :update]
  resources :comments, :only => [:create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :name,
    length: { minimum: 1, maximum: 10 },
    presence: true
  
  validates :introduction,
    length: {maximum: 140}



  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :avatar
  has_many :posts
  has_many :dogs
  has_many :comments
  has_many :likes
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  def after_update_path_for(resource)
    user_path(current_user.id)
  
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user=User.find(params[:id])
    @posts = @user.posts.includes(:likes).with_attached_images
    @dogs = @user.dogs.with_attached_avatar
    @dog = Dog.new
    @like_length = 0
    @posts.each do |post|
      @like_length += post.likes.length
    end
    
  end

  def index
    @users = User.with_attached_avatar
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<%= render partial: "/modules/header"%>
<div class="user_index grandPart">
  <div class="container-fluid">
    <div class="row user_index__row">
      <div class="col-xs-12 col-sm-12 col-md-4">
      </div>
      <div class="col-xs-12 col-sm-12 col-md-4 main">
        <div class="main__title">
          ユーザー
        </div>
        <div class="main__serchbox">
          <input type="email" class="form-control" id="exampleInputEmail1" placeholder="検索">
        </div>
        <div class="main__users">

          <% @users.each do |user|%>
          <div class="main__users-user">
            <%unless user.avatar.attached?%>
            <i class="fas fa-user-circle fa-3x"></i>
            <%else%>
            <%= image_tag user.avatar.variant(combine_options:{resize:"50x50^",crop:"50x50+0+0",gravity: :center}).processed, class: "avatar-large"%>
            <%end%>
            <div class="main__users-user-name">
              <%= link_to user.name, user_path(user.id), class: "user_name"%>
              <div class="dog_name" href="#">Dog_name</div>
            </div>
          </div>
          <%end%>

        </div>
      </div>
    </div>
  </div>
</div>
</div>

app/views/users/show.html.erb
<%= render partial: "/modules/header"%>
<div class="user_show grandPart">
  <div class="main">
    <div class="main__title">
      <div class="main__title-content">
        <%if @user.avatar.attached?%>
        <%= image_tag @user.avatar.variant(combine_options:{resize:"200x200^",crop:"200x200+0+0",gravity: :center}).processed, class: "avatar-large"%>
        <%else%>
        <i class="fas fa-user-circle fa-8x"></i>
        <%end%>
        <div class="main__title-content-profile">
          <div class="name">
            <p><%= @user.name%></p>
            <%if current_user && @user.id == current_user.id%>
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal-edit">編集</button>
            <button type="button" class="btn btn-primary" data-toggle="modal"
              data-target="#myModal-add">MyDoggyを追加</button>
            <%end%>
          </div>

          <div class="info">
            <div><i class="fas fa-heart fa-2x"></i><%=@like_length%></div>
            <div><i class="fas fa-sticky-note fa-2x"></i> <%=@user.posts.length%></div>
          </div>
          <div class="selfintroduction">
            <%= simple_format(@user.introduction)%>
          </div>
        </div>
      </div>

      <div class="modal fade" id="myModal-edit" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">ユーザー情報編集</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="閉じる">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">

              <%= form_for(@user, url: user_registration_path, html: { method: :put }) do |f| %>
              <%unless @user.avatar.attached?%>
              <i class="fas fa-user-circle fa-3x"></i>
              <%else%>
              <%= image_tag @user.avatar.variant(combine_options:{resize:"50x50^",crop:"50x50+0+0",gravity: :center}).processed, class: "avatar-large"%>
              <%end%>
              <i class="fas fa-image fa-lg" id="file_image"></i>
              <%= f.file_field :avatar ,class: "hide", id: "file_image_input"%>
              <p>ユーザーネーム</p>
              <%= f.text_field :name, value: "#{@user.name}", placeholder: "ユーザーネーム"%>
              <p>メールアドレス</p>
              <%= f.email_field :email, autofocus: true, autocomplete: "email", placeholder: "Email", value: "#{@user.email}"%>
              <p>一言プロフィール</p>
              <%= f.text_area :introduction, autocomplete: "text",value: "#{@user.introduction}", rows: "5"%>
              <p>現在のパスワード</p>
              <%= f.password_field :current_password, autocomplete: "current-password" %>
              <br><a href="#" id="open_passform" class="">パスワードを変更する</a>
              <div class="hide" id="closed_passform">
                <p>新しいパスワード</p>
                <%= f.password_field :password, autocomplete: "new-password" %>
                <p>新しいパスワード（確認）</p>
                <%= f.password_field :password_confirmation, autocomplete: "new-password" %>

              </div>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">閉じる</button>
              <%= f.submit "変更を保存", class: "btn btn-primary"%>
              <%end%>
            </div>
          </div>
        </div>
      </div>


      <div class="modal fade" id="myModal-add" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">MyDoggyを追加</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="閉じる">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <%=form_for(@dog, url: dogs_path) do |f|%>
            <div class="modal-body">
              <i class="fas fa-image fa-2x" id="dog_image"></i>
              <%= f.file_field :avatar ,class: "hide", id: "dog_image_input"%>
              <p>Doggyネーム</p>
              <%= f.text_field :name, placeholder: "Doggy_name"%>
              <p>プロフィール</p>
              <%= f.text_area :profile, rows: 5, placeholder: "140文字まで"%>
              <p>犬種を選択</p>
              <input placeholder="検索"></input>
            </div>

            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">閉じる</button>
              <%= f.submit "追加", class: "btn btn-primary"%>
            </div>
            <%end%>
          </div>
        </div>
      </div>

    </div>
    <div class="main__posts container">
      <div>
        <h3>MyDoggy</h3>
      </div>
      <div class="row">
        <%@dogs.each do |dog|%>
        <div class="col-sm-6 col-md-3">


          <div class="card img-thumbnail">
            <%if dog.avatar.attached?%>

            <%= image_tag dog.avatar.variant(combine_options:{resize:"245x200^",crop:"245x200+0+0",gravity: :center}).processed%>
            <%else%>
            <%= image_tag("/assets/dog.jpeg", :size => "245x200") %>
            <%end%>
            <div class="card-body px-2 py-3">
              <h5 class="card-title"><%=dog.name%>
                <% if current_user && current_user.id == @user.id%>
                <i class="fas fa-cog " data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></i>
                <%end%>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                  <%=link_to "詳細", dog_path(dog.id), class: "dropdown-item"%>
                  <%=link_to "削除","/dogs/#{dog.id}" , class: "dropdown-item",method: :delete%>
                </div>
              </h5>
              <p class="card-text"><%=simple_format(dog.profile)%></p>
            </div>
          </div>

        </div>
        <%end%>

      </div>
      <div>
        <h3>投稿一覧</h3>
      </div>
      <div class="row">
        <%@posts.each do |post|%>
        <div class="col-sm-6 col-md-3 post-image">
          <%= link_to(post_path(post.id), class: "card") do %>
          <%=image_tag(post.images[0].variant(combine_options:{resize:"253x253^",crop:"253x253+0+0",gravity: :center}).processed,class: "card-img")%>
          <%end%>
        </div>
        <%end%>


      </div>

    </div>
  </div>
</div>
<%= render partial:"/modules/footer"%>