config/routes.rb
Rails.application.routes.draw do
  get 'dogs/new'
  get 'posts/index'
  devise_for :users, controllers: {   registrations: 'users/registrations',
                                    sessions: 'users/sessions' }
  root "notes#index"
  resources :notes, only: [:index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :posts do
    resources :likes, :only => [:create, :destroy]
  end
  resources :users, :only => [:show,:index]
  resources :dogs, :only => [:create, :destroy, :update]
  resources :comments, :only => [:create, :destroy]
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many_attached :images
  has_many :tags, through: :post_tags
  has_many :comments
  has_many :likes
  acts_as_taggable
  validates :images,
    presence: true
  validates :text,
    length: {maximum: 200}
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.includes(comments: :user).includes(:tags).includes(:user).includes(:likes).with_attached_images.order(id: "DESC")
    @users = User.all.with_attached_avatar
    @comment = Comment.new
  end

  def create
    @post = Post.new(post_params)
    @post.save
    if @post.save
      redirect_to posts_path
    else
      redirect_to root_path
    end
  end

  def destroy
    post = Post.find(params[:id])
    unless current_user && post.user.id == current_user.id
      redirect_to root_path
    else 
      post.destroy
      redirect_to posts_path
    end
  end

  def show
    @post_show = Post.find(params[:id])
    @comment = Comment.new
  end

  private

  def post_params
    post_params_result=params.require(:post).permit(:tag_list,:text,images: []).merge(user_id: current_user.id)
    if post_params_result[:images].length > 4
      return nil
    else
      return post_params_result
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_postContent.html.erb
<div class="posts__puttogether " data-id="<%=id%>">
  <div class="post__maincontent-posts">
    <div class="post__maincontent-posts-title">
      <%unless post.user.avatar.attached?%>
      <i class="fas fa-user-circle fa-2x"></i>
      <%else%>
      <%= image_tag post.user.avatar.variant(combine_options:{resize:"32x32^",crop:"32x32+0+0",gravity: :center}).processed, class: "avatar-large"%>
      <%end%>
      <%=link_to "#{post.user.name}", user_path(post.user.id), class: "user_name"%>
      <div class="fas-modifier">
        <a href="#" role="button" id="dropdownMenuLink<%=id%>" data-toggle="dropdown" aria-haspopup="true"
          aria-expanded="false"><i class="fas fa-ellipsis-v"></i></a>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuLink<%=id%>">
          <%=link_to "詳細", post_path(post.id), class: "dropdown-item"%>
          <%if current_user && current_user.id == post.user.id%>
          <%=link_to "削除", "/posts/#{post.id}", class: "dropdown-item",method: :delete%>
          <%end%>
        </div>
      </div>
    </div>
    <div class="post__maincontent-posts-image">
      <div id="carouselExampleControls<%=id%>" class="carousel slide">

        <div class="carousel-inner">
          <%post.images.each_with_index do |image,index|%>
          <%if index == 0%>
          <div class="carousel-item active">
            <%=image_tag(image,class: "d-block w-100")%>
          </div>
          <%else%>
          <div class="carousel-item">
            <%=image_tag(image,class: "d-block w-100")%>
          </div>
          <%end%>
          <%end%>
        </div>
        <%if post.images.length >= 2%>
        <a class="carousel-control-prev" href="#carouselExampleControls<%=id%>" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">前へ</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleControls<%=id%>" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">次へ</span>
        </a>
        <%end%>
      </div>
    </div>
    <div class="post__maincontent-posts-icons">

      <%if user_signed_in?%>
      <%if Like.find_by(user_id: current_user.id, post_id: post.id)%>
      <%=link_to("/posts/#{post.id}/likes/#{current_user.id}", class: "post__maincontent-posts-icons-a", method: :delete) do%>
      <i class="fas fa-heart fa-2x pinked"></i>
      <%end%>
      <%else%>
      <%=link_to(post_likes_path(post.id), class: "post__maincontent-posts-icons-a", method: :post) do%>
      <i class="far fa-heart fa-2x"></i>
      <%end%>
      <%end%>
      <span><%=post.likes.length%></span>
      <%else%>
      <a class="post__maincontent-posts-icons-a"><i
          class="far fa-heart fa-2x"></i></a><span><%=post.likes.length%></span>
      <%end%>

      <a class="post__maincontent-posts-icons-a"><i
          class="far fa-comment fa-2x"></i></a><span><%=post.comments.length%></span>
    </div>
    <div class="post__maincontent-posts-text">
      <%=post.text[0,12]%>.....<a href="#" class="tuzuki" data-id="<%=id%>">すべて見る</a>
    </div>
    <% if user_signed_in?%>
    <%= form_for(@comment, url: comments_path, html: { method: :post }) do |f| %>
    <div class="post__maincontent-posts-commentform">
      <%= f.text_field :text, placeholder: "コメントを入力..."%>
    </div>
    <%= f.text_field :post_id, type: "hidden", value: "#{post.id}"%>
    <%= f.submit type: "hidden" %>
    <%end%>
    <%end%>

  </div>



  <div class="post__maincontent-posts hide">
    <div class="post__maincontent-posts-title">
      <%unless post.user.avatar.attached?%>
      <i class="fas fa-user-circle fa-2x"></i>
      <%else%>
      <%= image_tag post.user.avatar.variant(combine_options:{resize:"32x32^",crop:"32x32+0+0",gravity: :center}).processed, class: "avatar-large"%>
      <%end%>
      <%=link_to "#{post.user.name}", user_path(post.user.id), class: "user_name"%>
      <div class="fas-modifier">
        <a href="#" role="button" id="dropdownMenuLink<%=id%>" data-toggle="dropdown" aria-haspopup="true"
          aria-expanded="false"><i class="fas fa-ellipsis-v"></i></a>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuLink<%=id%>">
          <%=link_to "詳細", post_path(post.id), class: "dropdown-item"%>
          <%if current_user && current_user.id == post.user.id%>
          <%=link_to "削除", "/posts/#{post.id}", class: "dropdown-item",method: :delete%>
          <%end%>
        </div>
      </div>
    </div>
    <div class="post__maincontent-posts-image">
      <div id="carouselExampleControls<%=id%>h" class="carousel slide">

        <div class="carousel-inner">
          <%post.images.each_with_index do |image,index|%>
          <%if index == 0%>
          <div class="carousel-item active">
            <%=image_tag(image,class: "d-block w-100")%>
          </div>
          <%else%>
          <div class="carousel-item">
            <%=image_tag(image,class: "d-block w-100")%>
          </div>
          <%end%>
          <%end%>
        </div>
        <%if post.images.length >= 2%>
        <a class="carousel-control-prev" href="#carouselExampleControls<%=id%>h" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">前へ</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleControls<%=id%>h" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">次へ</span>
        </a>
        <%end%>
      </div>
    </div>
    <div class="post__maincontent-posts-icons">
      <%if user_signed_in?%>
      <%if Like.find_by(user_id: current_user.id, post_id: post.id)%>
      <%=link_to("/posts/#{post.id}/likes/#{current_user.id}", class: "post__maincontent-posts-icons-a", method: :delete) do%>
      <i class="fas fa-heart fa-2x pinked"></i>
      <%end%>
      <%else%>
      <%=link_to(post_likes_path(post.id), class: "post__maincontent-posts-icons-a", method: :post) do%>
      <i class="far fa-heart fa-2x"></i>
      <%end%>
      <%end%>
      <span><%=post.likes.length%></span>
      <%else%>
      <a class="post__maincontent-posts-icons-a"><i
          class="far fa-heart fa-2x"></i></a><span><%=post.likes.length%></span>
      <%end%>
      <a href="#" class="post__maincontent-posts-icons-a"><i
          class="far fa-comment fa-2x"></i></a><span><%=post.comments.length%></span>
    </div>
    <div class="post__maincontent-posts-text">
      <%=simple_format(post.text)%>
      <div class="post__maincontent-posts-hash">
        <%post.tags.each do |tag|%>
        <a href="#">#<%=tag%></a>
        <%end%>
      </div>
    </div>

    <div class="post__maincontent-posts-comments">
      <%post.comments.each do |comment|%>
      <div class="post__maincontent-posts-comments-comment">
        <div class="post__maincontent-posts-comments-comment-user">
          <%unless comment.user.avatar.attached?%>
          <i class="fas fa-user-circle fa-2x"></i>
          <%else%>
          <%= image_tag comment.user.avatar.variant(combine_options:{resize:"32x32^",crop:"32x32+0+0",gravity: :center}).processed, class: "avatar-large"%>
          <%end%>

          <%=link_to "#{comment.user.name}",user_path(comment.user.id),class: "user_name"%>
          <%if current_user && comment.user.id == current_user.id%>
          <i class="fas fa-trash-alt trush" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></i>
          <div class="dropdown-menu">
            <%=link_to "削除", comment_path(comment.id), method: :delete, class: "dropdown-item"%>
          </div>
          <%end%>
        </div>
        <div class="post__maincontent-posts-comments-comment-text">
          <%=comment.text%>
        </div>
      </div>
      <%end%>

    </div>
    <a href="#" class="oritatamu" data-id="<%=id%>">...おりたたむ</a>
    <% if user_signed_in?%>
    <%= form_for(@comment, url: comments_path, html: { method: :post }) do |f| %>
    <div class="post__maincontent-posts-commentform">
      <%= f.text_field :text, placeholder: "コメントを入力..."%>
    </div>
    <%= f.text_field :post_id, type: "hidden", value: "#{post.id}"%>
    <%= f.submit type: "hidden" %>
    <%end%>
    <%end%>

  </div>
</div>

app/views/posts/index.html.erb
<%= render partial: "/modules/header"%>
<div class="post grandPart">
  <div class="container-fluid post__mainContent">

    <div class="row post_row ">
      <div class="col-xs-0 col-sm-0 col-md-1 ">
      </div>

      <div class="post_row_left col-xs-12 col-sm-12 col-md-2 ">
        <%if current_user%>
        <div class="post__user">

          <%unless current_user.avatar.attached?%>
          <i class="fas fa-user-circle fa-3x"></i>
          <%else%>
          <%= image_tag current_user.avatar.variant(combine_options:{resize:"50x50^",crop:"50x50+0+0",gravity: :center}).processed, class: "avatar-large"%>
          <%end%>

          <div class="post__user-name">
            <p class="post__user-name_user"><%=current_user.name%></p>
            <p class="post__user-name_dog">Dog_name</p>
          </div>

        </div>
        <%end%>
        <div class="post__pickedUser">
          <%if @users%>
          <div class="post__pickedUser-title">
            <p class="osusume">おすすめ</p>
            <a href="/users" class="subete">すべて見る</a>
          </div>

          <div class="post__pickedUser-user">
            <%unless @users[0].avatar.attached?%>
            <i class="fas fa-user-circle fa-2x"></i>
            <%else%>
            <%= image_tag @users[0].avatar.variant(combine_options:{resize:"32x32^",crop:"32x32+0+0",gravity: :center}).processed, class: "avatar-large"%>
            <%end%>
            <%=link_to "#{@users[0].name}",user_path(@users[0].id),class: "user_name"%>
          </div>

          <div class="post__pickedUser-user">
            <%unless @users[1].avatar.attached?%>
            <i class="fas fa-user-circle fa-2x"></i>
            <%else%>
            <%= image_tag @users[1].avatar.variant(combine_options:{resize:"32x32^",crop:"32x32+0+0",gravity: :center}).processed, class: "avatar-large"%>
            <%end%>
            <%=link_to "#{@users[1].name}",user_path(@users[1].id),class: "user_name"%>
          </div>
          <div class="post__pickedUser-user">
            <%unless @users[2].avatar.attached?%>
            <i class="fas fa-user-circle fa-2x"></i>
            <%else%>
            <%= image_tag @users[2].avatar.variant(combine_options:{resize:"32x32^",crop:"32x32+0+0",gravity: :center}).processed, class: "avatar-large"%>
            <%end%>
            <%=link_to "#{@users[2].name}",user_path(@users[2].id),class: "user_name"%>
          </div>
          <%end%>
        </div>
      </div>
      <div class="post_row_right col-xs-12 col-sm-6 ">
        <%@posts.each_with_index do |post,id|%>
        <%= render partial: "postContent", locals: {id: id, post: post}%>
        <%end%>
      </div>

    </div>
  </div>
</div>

<%= render partial:"/modules/footer"%>

app/views/posts/show.html.erb
<%= render partial: "/modules/header"%>
<div class="post grandPart">
  <div class="container-fluid post__mainContent">
    <div class="row post_row ">

      <div class="post_row_left col-xs-12 col-sm-12 col-md-3 ">
      </div>

      <div class="post_row_right col-xs-12 col-sm-6 ">

        <div class="post__maincontent-posts">
          <div class="post__maincontent-posts-title">
            <%unless @post_show.user.avatar.attached?%>
            <i class="fas fa-user-circle fa-2x"></i>
            <%else%>
            <%= image_tag @post_show.user.avatar.variant(combine_options:{resize:"32x32^",crop:"32x32+0+0",gravity: :center}).processed, class: "avatar-large"%>
            <%end%>
            <%=link_to "#{@post_show.user.name}", user_path(@post_show.user.id), class: "user_name"%>
            <div class="fas-modifier">
              <a href="#" role="button" id="dropdownMenuLink1" data-toggle="dropdown" aria-haspopup="true"
                aria-expanded="false"><i class="fas fa-ellipsis-v"></i></a>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuLink1">
                <%=link_to "詳細", post_path(@post_show.id), class: "dropdown-item"%>
                <%if current_user && current_user.id && current_user.id == @post_show.user.id%>
                <%=link_to "削除", "/posts/#{@post_show.id}", class: "dropdown-item",method: :delete%>
                <%end%>
              </div>
            </div>
          </div>
          <div class="post__maincontent-posts-image">
            <div id="carouselExampleControls1h" class="carousel slide">

              <div class="carousel-inner">
                <%@post_show.images.each_with_index do |image,index|%>
                <%if index == 0%>
                <div class="carousel-item active">
                  <%=image_tag(image,class: "d-block w-100")%>
                </div>
                <%else%>
                <div class="carousel-item">
                  <%=image_tag(image,class: "d-block w-100")%>
                </div>
                <%end%>
                <%end%>
              </div>

              <a class="carousel-control-prev" href="#carouselExampleControls1h" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">前へ</span>
              </a>
              <a class="carousel-control-next" href="#carouselExampleControls1h" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">次へ</span>
              </a>
            </div>
          </div>
          <div class="post__maincontent-posts-icons">
            <a href="#" class="post__maincontent-posts-icons-a"><i class="far fa-heart fa-2x"></i></a><span>12</span>
            <a class="post__maincontent-posts-icons-a"><i
                class="far fa-comment fa-2x"></i></a><span><%=@post_show.comments.length%></span>
          </div>
          <div class="post__maincontent-posts-text">
            <%=simple_format(@post_show.text)%>
            <div class="post__maincontent-posts-hash">
              <%@post_show.tags.each do |tag|%>
              <a href="#">#<%=tag%></a>
              <%end%>

            </div>
          </div>
          <div class="post__maincontent-posts-comments">
            <%@post_show.comments.each do |comment|%>
            <div class="post__maincontent-posts-comments-comment">
              <div class="post__maincontent-posts-comments-comment-user">
                <%unless comment.user.avatar.attached?%>
                <i class="fas fa-user-circle fa-2x"></i>
                <%else%>
                <%= image_tag comment.user.avatar.variant(combine_options:{resize:"32x32^",crop:"32x32+0+0",gravity: :center}).processed, class: "avatar-large"%>
                <%end%>

                <%=link_to "#{comment.user.name}",user_path(comment.user.id),class: "user_name"%>
              </div>
              <div class="post__maincontent-posts-comments-comment-text">
                <%=comment.text%>
              </div>
            </div>
            <%end%>
            <% if user_signed_in?%>
            <%= form_for(@comment, url: comments_path, html: { method: :post }) do |f| %>
            <div class="post__maincontent-posts-commentform">
              <%= f.text_field :text, placeholder: "コメントを入力..."%>
            </div>
            <%= f.text_field :post_id, type: "hidden", value: "#{@post_show.id}"%>
            <%= f.submit type: "hidden" %>
            <%end%>
            <%end%>

          </div>

        </div>
      </div>
    </div>
  </div>



  <%= render partial: "/modules/footer"%>